# -*- coding: utf-8 -*-
"""data science .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjF4vGILOvni_V5GNc5d3AmPp4roYHrj
"""

# Personal Introduction Program

# Ask for user inputs
name = input("Enter your name: ")
age = input("Enter your age: ")
hobby = input("Enter your hobby: ")

# Display the result
print("\nHello " + name + "! 👋")
print("You are " + age + " years old and you love " + hobby + ".")
print("Welcome to this program — great to meet you!")

project -2

# 🎓 Student Grade Calculator 🎓

print("Welcome to the Student Grade Calculator!")
print("----------------------------------------")

# Step 1: Get marks from the user
marks = float(input("Enter your marks (0-100): "))

# Step 2: Validate the input
if marks < 0 or marks > 100:
    print("❌ Invalid input! Please enter marks between 0 and 100.")
else:
    # Step 3: Use if-else to find the grade
    if marks >= 90:
        grade = "A"
        message = "Excellent work! 🌟"
    elif marks >= 80:
        grade = "B"
        message = "Great job! Keep it up! 👍"
    elif marks >= 70:
        grade = "C"
        message = "Good effort! You can do even better! 💪"
    elif marks >= 60:
        grade = "D"
        message = "You passed, but aim higher next time! 🎯"
    else:
        grade = "F"
        message = "Don’t give up — keep practicing! 📘"

    # Step 4: Show the result
    print(f"\nYour Grade: {grade}")
    print(f"Feedback: {message}")